version: '3.5'
volumes:
  postgres:

services:
  app:
    container_name: checkout-service-app
    #image: bigsmilez/inconvenio-webshop:checkout-service
    command: java -jar target/checkout-microservice-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_checkout:5434/postgres
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_RABBITMQ_HOST=inconv-rabbit-mq
      - SERVER_PORT=8090
    depends_on:
      - postgres
    networks:
      - backend
  postgres:
    container_name: postgres_checkout
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGPORT: 5434
      PGDATA: /postgres
    volumes:
      - postgres:/postgres
    ports:
      - "5434:5434"
    restart: unless-stopped
    networks:
      - backend
networks:
  backend:
    driver: bridge
    external: true
    name: backend